version: '3.6'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    command: "mix run --no-halt"
    ports:
      - "4000:4000"
    tty: true
    volumes:
      - .:/app

    links:
      - db:db

    environment:
      IN_DOCKER: "true"
      POSTGRES_DB: "tabular"
      POSTGRES_DB_USER: "postgres"
      POSTGRES_DB_PASSWORD: "the-cake-is-a-lie"
      POSTGRES_DB_HOST: "db"
      POSTGRES_DB_POOL_SIZE: "20"

  db:
    image: postgres:9.6.0
    volumes:
      - ./docker-entrypoint-initdb.d/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh:rw
    environment:
      POSTGRES_PASSWORD: "the-cake-is-a-lie"
